apiVersion: apps/v1
kind: Deployment
metadata:
  name: sampleapp
  labels:
    app: sampleapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: sampleapp
        # Replace <your-container-registry> with your actual container registry
        image: thisadee.azurecr.io/azure-pipelines-canary-k8s:latest
        ports:
        - containerPort: 8000
        - containerPort: 8080
        env: 
        - name: SUCCESSES_RATE
          value: "2"
      imagePullSecrets:
      - name: my-acr-secret